// <auto-generated />
using System;
using ColorDash.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColorDash.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426085535_AddStartIdempotencyKey")]
    partial class AddStartIdempotencyKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ColorDash.Api.Domain.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("correct_count");

                    b.Property<int>("CorrectIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("correct_index");

                    b.PrimitiveCollection<string>("CurrentColors")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("current_colors");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<string>("EndResponseJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ended_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("LastGuessIdempotencyKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastGuessResponseJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("mode");

                    b.Property<int>("ScorePoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score_points");

                    b.Property<int>("ScoreTotal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score_total");

                    b.Property<string>("StartIdempotencyKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("TriesLeft")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tries_left");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_game_sessions_device_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_game_sessions_expires_at");

                    b.ToTable("game_sessions", (string)null);
                });

            modelBuilder.Entity("ColorDash.Api.Domain.Highscore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("achieved_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("mode");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER")
                        .HasColumnName("points");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("DeviceId", "Mode")
                        .IsUnique()
                        .HasDatabaseName("ix_highscores_device_id_mode");

                    b.ToTable("highscores", (string)null);
                });

            modelBuilder.Entity("ColorDash.Api.Domain.Highscore", b =>
                {
                    b.HasOne("ColorDash.Api.Domain.GameSession", "Session")
                        .WithOne("Highscore")
                        .HasForeignKey("ColorDash.Api.Domain.Highscore", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ColorDash.Api.Domain.GameSession", b =>
                {
                    b.Navigation("Highscore");
                });
#pragma warning restore 612, 618
        }
    }
}
