// <auto-generated />
using System;
using ColorDash.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ColorDash.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ColorDash.Api.Domain.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("correct_count");

                    b.Property<int>("CorrectIndex")
                        .HasColumnType("integer")
                        .HasColumnName("correct_index");

                    b.PrimitiveCollection<string>("CurrentColors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("current_colors");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("EndResponseJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("LastGuessIdempotencyKey")
                        .HasColumnType("text");

                    b.Property<string>("LastGuessResponseJson")
                        .HasColumnType("text");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("mode");

                    b.Property<int>("ScorePoints")
                        .HasColumnType("integer")
                        .HasColumnName("score_points");

                    b.Property<int>("ScoreTotal")
                        .HasColumnType("integer")
                        .HasColumnName("score_total");

                    b.Property<string>("StartIdempotencyKey")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TriesLeft")
                        .HasColumnType("integer")
                        .HasColumnName("tries_left");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_game_sessions_device_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_game_sessions_expires_at");

                    b.HasIndex("DeviceId", "StartIdempotencyKey")
                        .HasDatabaseName("ix_game_sessions_device_id_start_key");

                    b.ToTable("game_sessions", (string)null);
                });

            modelBuilder.Entity("ColorDash.Api.Domain.Highscore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("achieved_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("mode");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("Total")
                        .HasColumnType("integer")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("DeviceId", "Mode")
                        .IsUnique()
                        .HasDatabaseName("ix_highscores_device_id_mode");

                    b.ToTable("highscores", (string)null);
                });

            modelBuilder.Entity("ColorDash.Api.Domain.Highscore", b =>
                {
                    b.HasOne("ColorDash.Api.Domain.GameSession", "Session")
                        .WithOne("Highscore")
                        .HasForeignKey("ColorDash.Api.Domain.Highscore", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ColorDash.Api.Domain.GameSession", b =>
                {
                    b.Navigation("Highscore");
                });
#pragma warning restore 612, 618
        }
    }
}
